[versions]
minecraft = "1.21.7"
paper-api = "1.21.7-R0.1-SNAPSHOT"
tinyloki = "1.1.8"
shadow = "8.3.8"
userdev = "2.0.0-beta.18"

[libraries]
tinyloki = { module = "io.github.mjfryc:mjaron-tinyloki-java", version.ref = "tinyloki" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
paperweight-userdev = { id = "io.papermc.paperweight.userdev", version.ref = "userdev" }
